### ISSUE TITLE
I broke /admin/overview/hosts

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#258]
It was working in 5aa1134 on my local machine, but after I pushed to production, it broke. Can we fix this? And while we're at it, also handle #250

**Comment by mehulkar** [comment]
Loaded /admin/overview/hosts route locally and it seems to work fine. @ankitshah811 can you verify that this is still broken?

![screen shot 2015-04-23 at 11 16 10 pm](https://cloud.githubusercontent.com/assets/490968/7311781/c3595220-ea0e-11e4-87e7-4706556b1cd9.png)

**Comment by nickbarnwell** [comment]
It works in production now, IIRC I hotfixed it and this probably got lost in the GH <----> Trello shuffle.

What we really need is a plan to deprecate the admin pages and move to another method

a) that runs out of the web process, since computing these queries (esp. the way I'm doing them in these controllers) is sloooow.

b) Provide info in an actionable format. I'd love to actually get a proper dashboard/statsd style reporting system in place along w. weekly/daily/monthly/what-have-you activity reports. Same queries could be used to let users know about upcoming tea times in their areas :)

**Comment by ankitshah811** [comment]
@mehulkar not broken anymore
@nickbarnwell to have an actionable dashboard would be A+
