### ISSUE TITLE
When logged out "Join" link at bottom of host page doesn't work

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#286]
The html says "Remove after Forbes/Inc". Not sure if that is related. 

![screen shot 2015-03-30 at 1 10 54 am](https://cloud.githubusercontent.com/assets/490968/6890454/9bf48964-d679-11e4-8875-6fd9ec0d0d54.png)

Talking about the yellow join link at the bottom.

**Comment by nickbarnwell** [comment]
That is because that is a header and not a button, I think…I have no recollection of writing that partial and looking at the code I am now sad. (app/views/shared/_tea_times.html.haml)

@ankitshah811 what'd you want to do here?

**Comment by ankitshah811** [comment]
It's only supposed to show up there if there are tea times under it. Right now, if I understand correctly, it shows up because there are future tea times >2wks out, which is why no tea times are actually showing up there. 

Quick sol'n = only show partial if there are tea times in the next two weeks. So in this case, the header shouldn't even be there

**Comment by mehulkar** [comment]
not relevant with new design. well, kinda still is, but won't be when new city pages are implemented.
