### ISSUE TITLE
fix tea time sign up modal 

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/tws-on-rails#434]
according to @ankitshah811 it loads the entire page instead of just a partial. or something like that. look into it before deploy.

**Comment by jermspeaks** [comment]
Figured it out. You weren't using the correct selector nor using the correct attribute caller for that selector.  

However, the fix I proposed in PR #517 shows an ugly modal window. Want someone to code review it and fix the margin issue in the modal before the change is pushed up.

![screenshot of error](http://i.imgur.com/jgF3Ngt.png)

**Comment by mehulkar** [comment]
@jermspeaks thanks for the effort, but this issue was already fixed. Sorry for not closing it :cry:

**Comment by ankitshah811** [comment]
@mehulkar @jermspeaks I don't remember that this issue was effectively
fixed. We just created a BS workaround by eliminating the nav bar and other
page elements so that it would fit in the modal. This was subpar, as it
disallowed us to create distinct tea time pages (e.g.
http://teawithstrangers.com/tea_times/42 would *only* look good in a modal,
but we couldn't send someone to that page directly without it looking dumb).

If Jeremy's fix allows for us to render a full page and also keep the modal
in tact as necessary, that would be great, as it permits us to manage sign
up, log in, canceling tea time spots and potentially some other future
features in modals while still maintaining the integrity of the standalone
pages that exist outside the scope of a modal. If that's the case, can we
proceed with this? And Jeremy, could you make it clear what design changes
you'd need from me to ensure this is implemented optimally?

Also, can we ensure that if/when we bring modals back, that they *never* show
up on mobile? Horrible experience for mobile, but if we can keep the
standalone pages in tact, then we can ensure a quality experience for all

**Comment by jermspeaks** [comment]
If I'm hearing you correctly, you want modals for partials, but you don't want them to show up mobile (or, if we think of this responsively, past a certain viewport width). An alternative would be an [inline accordion](http://uxmovement.com/mobile/why-you-should-avoid-using-modal-windows-on-mobile/).

But, if you go with separate, full page approach on mobile, you also have to think about state. Does the route change after you are taken to this full page while on mobile, but just a modal on a web browser?
For Rails, I'm not sure what the optimal solution here is (AJAX-ify everything)?

Design-wise, if all partials are created with [relative units](https://developer.mozilla.org/en-US/docs/Web/CSS/length) rather than absolute units, create proper padding and margins accordingly, we could have consistency around all devices.

**Comment by ankitshah811** [comment]
@jermspeaks Great points. I think the inline accordion looks cool, but there's one of the big issues with it is form submission on a page that isn't dedicated to forms can be confusing, and our site doesn't yet feel like a user would expect inline forms to be working (I don't know how to explain this well beyond just...it doesn't feel super slick)

I think the route should change on mobile b/c it would be a diff page + should just be a modal on tablet/desktop. 

Almost the entire website is already using relative units
