### ISSUE TITLE
User can sign up for the same tea time twice, then can't cancel seat

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#480]
I can't seem to cancel either of the user's attendance instances. When I try, I get the second screen seen here. 

* [x] Can you cancel one of the attendance instances via console @mehulkar? 
* [ ] Can we fix the underlying issue that allows this to happen in the first place?

![screenshot 2015-06-19 02 36 37](https://cloud.githubusercontent.com/assets/1022843/8250853/3a282022-162c-11e5-8103-abd9ff13261e.png)

![screenshot 2015-06-19 02 40 45](https://cloud.githubusercontent.com/assets/1022843/8250904/9ddba38c-162c-11e5-8f0f-475f8e6c24bc.png)

**Comment by nickbarnwell** [comment]
You're getting the error because the validation fires and throws an error, per `Attendance.rb:9`

`validates_uniqueness_of :user_id, scope: :tea_time_id`. I don't see how a duplicate record could've been created for this except via the console. It's possible the underlying code has changed in the interim, but I don't want to dig through history to find it.
