### ISSUE TITLE
Emails are still broken!!

### ISSUE THREAD

**Issue by ankitshah811** [TeaWithStrangers/tws-on-rails#529]
got this message from a host just now, but totally thought bug was fixed with yesterday's deployment. thoughts @mehulkar, @nickbarnwell ?
![image](https://cloud.githubusercontent.com/assets/1022843/8634820/6b956d52-27bd-11e5-8d26-932cda0913af.jpg)

**Comment by mehulkar** [comment]
probably because her reminders were queued before we deployed the fix

**Comment by ankitshah811** [comment]
can we confirm this in logs? or at the least, confirm that we're not
experiencing the same issues?

**Comment by mehulkar** [comment]
mayyy be able to look up things in logs. problem is that these events
didn't all happen at the same time, so tracking down all the appropriate
logs may or may not be possible.


------
Mehul Kar
@mehulkar

**Comment by kylechadha** [comment]
I received ten "Mark your attendance" e-mails for a tea time I did last night. It was scheduled prior to the fix on Fri, but I guess the question is when the "Mark your attendance" e-mails are scheduled -- on event creation or occurrence?

@mehulkar let me know if there's anything I can look into

**Comment by mehulkar** [comment]
@kylechadha there was a bug where we queued the "mark your attendance" reminder on every _update_ to the tea time, so it would have queued the same email multiple times. That bug was fixed in #521, but it doesn't affect emails that were queued before because we didn't have any insight into queued jobs :cry: . I also deployed an admin interface for delayed jobs in #534 to help with that, but haven't actually looked at it yet. Not sure if it will help with old queued jobs anyway. 

> let me know if there's anything I can look into

lots you can look into! One thing is we need to change how we "queue" emails at certain times and instead run a cron job every night. Right now, if an email is queued, it gets queued and nothing can change it. So if you change the day/time of your teatime, the emails will be queued for the wrong times. That needs to be fixed.

**Comment by mehulkar** [comment]
Unrelated to emails, there are also a bunch of smaller bugs in the Issues list that you could knock out pretty quick

**Comment by mehulkar** [comment]
this should be fixed now. see teawithstrangers.com/admin/jobs for more insight into jobs that were scheduled before this was fixed.
